# LINEAR CLASSIFICATION AND LOGISTIC REGRESSION

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [14]:
df = pd.read_csv('C:\\Users\\HP\\Downloads\\hamoye\\dataset\\NFA 2019 public_data.csv')

df.head()

c:\users\hp\downloads\python\lib\site-packages\IPython\core\interactiveshell.py:3062: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


country  year  country_code        record      crop_land   grazing_land  \
0  Armenia  1992             1    AreaPerCap       0.140292       0.199546   
1  Armenia  1992             1     AreaTotHA  483000.000000  687000.000000   
2  Armenia  1992             1  BiocapPerCap       0.159804       0.135261   
3  Armenia  1992             1  BiocapTotGHA  550176.242700  465677.972200   
4  Armenia  1992             1  EFConsPerCap       0.387510       0.189462   

   forest_land  fishing_ground  built_up_land    carbon         total QScore  
0  0.097188051        0.036888       0.029320  0.000000  5.032351e-01     3A  
1       334600   127000.000000  100943.000800  0.000000  1.732543e+06     3A  
2  0.084003213        0.013742       0.033398  0.000000  4.262086e-01     3A  
3  289207.1078    47311.551720  114982.279300  0.000000  1.467355e+06     3A  
4     1.26E-06        0.004165       0.033398  1.114093  1.728629e+00     3A

In [15]:
df['QScore'].value_counts()

3A    51481
2A    10576
2B    10096
1A       16
1B       16
Name: QScore, dtype: int64

In [16]:
df.isna().sum()

country               0
year                  0
country_code          0
record                0
crop_land         20472
grazing_land      20472
forest_land       20472
fishing_ground    20473
built_up_land     20473
carbon            20473
total                 9
QScore                1
dtype: int64

In [17]:
df=df.dropna()
df.isna().sum()

country           0
year              0
country_code      0
record            0
crop_land         0
grazing_land      0
forest_land       0
fishing_ground    0
built_up_land     0
carbon            0
total             0
QScore            0
dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 51713 entries, 0 to 72185
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   country         51713 non-null  object 
 1   year            51713 non-null  int64  
 2   country_code    51713 non-null  int64  
 3   record          51713 non-null  object 
 4   crop_land       51713 non-null  float64
 5   grazing_land    51713 non-null  float64
 6   forest_land     51713 non-null  object 
 7   fishing_ground  51713 non-null  float64
 8   built_up_land   51713 non-null  float64
 9   carbon          51713 non-null  float64
 10  total           51713 non-null  float64
 11  QScore          51713 non-null  object 
dtypes: float64(6), int64(2), object(4)
memory usage: 5.1+ MB


In [19]:
df['QScore'].value_counts()

3A    51473
2A      224
1A       16
Name: QScore, dtype: int64

In [46]:
df['QScore']=df['QScore'].replace(['1A'],'2A')
df.QScore.value_counts()

3A    51473
2A      240
Name: QScore, dtype: int64

In [47]:
df_2A = df[df.QScore=='2A']
df_3A = df[df.QScore=='3A'].sample(350, random_state=1)
data_df = df_2A.append(df_3A).reset_index(drop=True)
data_df.head()

country  year  country_code        record     crop_land  grazing_land  \
0  Algeria  2016             4    AreaPerCap  2.072989e-01  8.112722e-01   
1  Algeria  2016             4     AreaTotHA  8.417600e+06  3.294260e+07   
2  Algeria  2016             4  BiocapPerCap  2.021916e-01  2.636077e-01   
3  Algeria  2016             4  BiocapTotGHA  8.210214e+06  1.070408e+07   
4  Algeria  2016             4  EFConsPerCap  6.280528e-01  1.810332e-01   

   forest_land  fishing_ground  built_up_land    carbon         total QScore  
0  0.048357265        0.022585   2.998367e-02  0.000000  1.119497e+00     2A  
1      1963600   917100.000000   1.217520e+06  0.000000  4.545842e+07     2A  
2  0.027166736        0.007948   2.924496e-02  0.000000  5.301590e-01     2A  
3  1103135.245   322736.916200   1.187524e+06  0.000000  2.152769e+07     2A  
4  0.162800822        0.014729   2.924496e-02  1.391455  2.407316e+00     2A

In [48]:
import sklearn.utils
data_df = sklearn.utils.shuffle(data_df, random_state=1)
data_df = data_df.reset_index(drop=True)
data_df.shape
data_df.QScore.value_counts()

3A    350
2A    240
Name: QScore, dtype: int64

In [49]:
#more preprocessing
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
data_df.record = encoder.fit_transform(data_df.record)
data_df.QScore = encoder.fit_transform(data_df.QScore)
data_df.record, data_df.QScore

(0      3
 1      0
 2      7
 3      3
 4      2
       ..
 585    1
 586    0
 587    0
 588    3
 589    5
 Name: record, Length: 590, dtype: int32,
 0      1
 1      1
 2      0
 3      1
 4      0
       ..
 585    0
 586    0
 587    0
 588    0
 589    0
 Name: QScore, Length: 590, dtype: int32)

In [50]:
data_df = data_df.drop(columns=['country_code', 'country', 'year'])
X = data_df.drop(columns = 'QScore')
y = data_df['QScore']

In [51]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)
y_train.value_counts()

1    248
0    165
Name: QScore, dtype: int64

In [52]:
#encode categorical variable
import imblearn
from imblearn.over_sampling import SMOTE
smote=SMOTE(random_state=1)
x_train_balanced,y_balanced=smote.fit_sample(x_train,y_train)
y_balanced.value_counts()

1    248
0    248
Name: QScore, dtype: int64

In [53]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
normalized_train_df=scaler.fit_transform(x_train_balanced.drop(columns=['record']))
normalized_train_df=pd.DataFrame(normalized_train_df,columns=x_train_balanced.drop(columns=['record']).columns)
normalized_train_df['record']=x_train_balanced['record']
x_test=x_test.reset_index(drop=True)
y_test=y_test.reset_index(drop=True)

normalized_test_df=scaler.transform(x_test.drop(columns=['record']))
normalized_test_df=pd.DataFrame(normalized_test_df,columns=x_test.drop(columns=['record']).columns)
normalized_test_df['record']=x_test['record']
#Logistic Regression


In [54]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()
log_reg.fit(normalized_train_df ,y_balanced)
new_predictions=log_reg.predict(normalized_test_df)

# Measuring Classification Performance


Cross-validation and accuracy

In [55]:
from sklearn.model_selection import cross_val_score
scores= cross_val_score(log_reg,normalized_train_df,y_balanced,cv=7,scoring='f1_macro')
scores*100

array([59.93730408, 36.61971831, 47.72139303, 43.65079365, 61.85074627,
       56.08247423, 51.42857143])

confusion matrix

In [56]:
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
new_predictions=log_reg.predict(normalized_test_df)
cnf_mat=confusion_matrix(y_true=y_test,y_pred=new_predictions)
cnf_mat

array([[39, 36],
       [41, 61]], dtype=int64)

In [57]:
print("%.0f is the number of True Positive (TP)" % (cnf_mat[0, 0]))
print("%.0f is the number of False Positive (FP)" % (cnf_mat[0, 1]))
print("%.0f is the number of False Negative (FN)" % (cnf_mat[1, 0]))
print("%.0f is the number of True Negative (TN)" % (cnf_mat[1, 1]))

39 is the number of True Positive (TP)
36 is the number of False Positive (FP)
41 is the number of False Negative (FN)
61 is the number of True Negative (TN)


# METRICS

Accuracy

In [58]:
accuracy=accuracy_score(y_true=y_test,y_pred=new_predictions)
print('Accuracy:{}'.format(round(accuracy*100,2)))

Accuracy:56.5


Precision

In [59]:
precision=precision_score(y_true=y_test,y_pred=new_predictions)
print('Precision:{}'.format(round(precision*100),2))

Precision:63


Recall

In [60]:
Recall=recall_score(y_true=y_test,y_pred=new_predictions)
print('Recall:{}'.format(round(Recall*100),2))

Recall:60


In [ ]:
F1-score

In [61]:
f1=f1_score(y_true=y_test,y_pred=new_predictions)
print('f1:{}'.format(round(f1*100),2))

f1:61


K-Fold Cross Validation

In [63]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5)
kf.split(normalized_train_df)
#metric lists to hold the values calculated for every k-fold carried out
f1_scores, accuracy_kfold, precision_kfold, recall_kfold = [], [], [], []
kmodel = []

#run for every split
for train_index, test_index in kf.split(normalized_train_df):
    kx_train, kx_test = normalized_train_df.iloc[train_index],\
                      normalized_train_df.iloc[test_index]
    ky_train, ky_test = y_balanced[train_index],\
                      y_balanced[test_index]
    model = LogisticRegression().fit(kx_train, ky_train)
    #save result to list
    f1_scores.append(f1_score(y_true = ky_test, y_pred = model.predict(kx_test)))
    accuracy_kfold.append(accuracy_score(y_true=ky_test, y_pred=model.predict(kx_test)))
    precision_kfold.append(precision_score(y_true = ky_test, y_pred = model.predict(kx_test), zero_division=True))
    recall_kfold.append(recall_score(y_true = ky_test, y_pred = model.predict(kx_test)))
    pred = model.predict(kx_test)
    kmodel.append(pred)

In [64]:
classification_scores=pd.DataFrame([accuracy_kfold,precision_kfold,recall_kfold,f1_scores], index=['Accuracy','Precision','Recall','f1_scores'],columns=['k1','k2','k3','k4','k5'])
classification_scores

k1        k2        k3        k4        k5
Accuracy   0.430000  0.404040  0.454545  0.424242  0.131313
Precision  1.000000  0.424242  1.000000  0.647059  0.131313
Recall     0.033898  0.259259  0.100000  0.177419  1.000000
f1_scores  0.065574  0.321839  0.181818  0.278481  0.232143

Classification report

In [65]:
from sklearn.metrics import classification_report
if len(ky_test)!= len(kmodel[0]):
    kmodels=kmodel[0][:-1]
    print(classification_report(ky_test,kmodels))
else:
    print(classification_report(ky_test,kmodel[0]))

              precision    recall  f1-score   support

           0       0.88      0.99      0.93        86
           1       0.50      0.08      0.13        13

    accuracy                           0.87        99
   macro avg       0.69      0.53      0.53        99
weighted avg       0.83      0.87      0.82        99



Stratified K-Fold Cross Validation

In [66]:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=5,shuffle=True,random_state=1)
f1_scores_skfold,accuracy_skfold,precision_skfold,recall_skfold,cnf_mtxS=[],[],[],[],[]
skmodel=[]
for train_index,test_index in skf.split(normalized_train_df,y_balanced):
    skx_train,skx_test=np.array(normalized_train_df)[train_index],\
    np.array(normalized_train_df)[test_index]
    sky_train,sky_test=y_balanced[train_index],\
    y_balanced[test_index]
    model=LogisticRegression().fit(skx_train,sky_train)
    f1_scores_skfold.append(f1_score(y_true=sky_test,y_pred=model.predict(skx_test)))
    accuracy_skfold.append(accuracy_score(y_true=sky_test,y_pred=model.predict(skx_test)))
    precision_skfold.append(precision_score(y_true=sky_test,y_pred=model.predict(skx_test),zero_division=True))
    recall_skfold.append(recall_score(y_true=sky_test,y_pred=model.predict(skx_test)))
    skmodel.append(model.predict(skx_test))

In [67]:
classification_scores2=pd.DataFrame([accuracy_skfold,precision_skfold,recall_skfold,f1_scores_skfold],index=['Accuracy','Precision','Recall','F1 scores'],columns=['sk1','sk2','sk3','sk4','sk5'])
classification_scores2

sk1       sk2       sk3       sk4       sk5
Accuracy   0.450000  0.535354  0.545455  0.545455  0.545455
Precision  0.441860  0.540000  0.543860  0.541667  0.540000
Recall     0.380000  0.540000  0.620000  0.530612  0.551020
F1 scores  0.408602  0.540000  0.579439  0.536082  0.545455

In [68]:
if len(sky_test)!=len(skmodel[0]):
    skmodels=skmodel[0][:-1]
    print(classification_report(sky_test,skmodels))
else:
        print(classification_report(sky_test,skmodel[0]))
    

              precision    recall  f1-score   support

           0       0.56      0.64      0.60        50
           1       0.57      0.49      0.53        49

    accuracy                           0.57        99
   macro avg       0.57      0.56      0.56        99
weighted avg       0.57      0.57      0.56        99



Leave One Out Cross Validation (LOOCV)

In [69]:
from sklearn.model_selection import LeaveOneOut
loo=LeaveOneOut()
scores=cross_val_score(LogisticRegression(),normalized_train_df,y_balanced,cv=loo,scoring='f1_macro')
average_score=scores.mean()*100
average_score

52.62096774193549

Tree-Based Methods and The Support Vector Machine

In [113]:
from sklearn.tree import DecisionTreeClassifier
dec_tree=DecisionTreeClassifier()
dec_tree.fit(normalized_train_df,y_balanced)
dec_pred=dec_tree.predict(normalized_test_df)

In [70]:
print("Accuracy score {}".format(round(accuracy_score(y_test, dec_pred), 2)))
print("Precision score {}".format(round(precision_score(y_test, dec_pred),2)))
print("Recall score {}".format(round(recall_score(y_test, dec_pred), 2)))
print("F1 score {}".format(round(f1_score(y_test, dec_pred),2)))

NameError: name 'dec_pred' is not defined

In [3]:
import numpy as np
import pandas as pd
import graphviz
from sklearn import tree
from sklearn.metrics import accuracy_score
data=pd.read_csv('C:\\Users\\HP\\Downloads\\hamoye\\dataset\\Data_for_UCI_named.csv', delimiter = ',')
data.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

XGBOOST

In [89]:
from xgboost import XGBRFClassifier
extreme=XGBRFClassifier(random_state=1)
extreme.fit(normalized_train_df,y_balanced)
extreme_pred=extreme.predict(normalized_test_df)


In [72]:
print(classification_report(y_test, extreme_pred))

              precision    recall  f1-score   support

           0       0.53      0.57      0.55        75
           1       0.67      0.63      0.65       102

    accuracy                           0.60       177
   macro avg       0.60      0.60      0.60       177
weighted avg       0.61      0.60      0.61       177



In [75]:
from xgboost import XGBClassifier
extreme1 = XGBClassifier(random_state=1)
extreme1.fit(normalized_train_df, y_balanced)
extreme1_pred = extreme1.predict(normalized_test_df)

In [76]:
print(classification_report(y_test, extreme1_pred))

              precision    recall  f1-score   support

           0       0.60      0.61      0.61        75
           1       0.71      0.70      0.70       102

    accuracy                           0.66       177
   macro avg       0.65      0.65      0.65       177
weighted avg       0.66      0.66      0.66       177



In [78]:
from lightgbm import LGBMClassifier
light = LGBMClassifier(random_state=1)
light.fit(normalized_train_df, y_balanced)
light_pred = light.predict(normalized_test_df)

In [79]:
print(classification_report(y_test, light_pred))

              precision    recall  f1-score   support

           0       0.58      0.57      0.58        75
           1       0.69      0.70      0.69       102

    accuracy                           0.64       177
   macro avg       0.64      0.63      0.63       177
weighted avg       0.64      0.64      0.64       177



In [81]:
from sklearn.ensemble import ExtraTreesClassifier
tree = ExtraTreesClassifier(random_state=1)
tree.fit(normalized_train_df, y_balanced)
tree_pred = tree.predict(normalized_test_df)

In [82]:
n_estimators = [10, 50, 100, 250, 400]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'sqrt', 'log2', None] 
hyperparameter_grid = {'n_estimators': n_estimators,
                       'min_samples_leaf': min_samples_leaf,
                       'min_samples_split': min_samples_split,
                       'max_features': max_features}

In [84]:
from sklearn.model_selection import RandomizedSearchCV
clf = RandomizedSearchCV(tree, hyperparameter_grid, random_state=1)
search = clf.fit(normalized_train_df, y_balanced)

In [85]:
search.best_params_.values()

dict_values([100, 9, 2, 'auto'])

In [86]:
tree_param = ExtraTreesClassifier(n_estimators=100, min_samples_split=9, 
                                 min_samples_leaf=2, max_features='auto', random_state=1)
tree_param.fit(normalized_train_df, y_balanced)
tree_param_pred = tree_param.predict(normalized_test_df)


In [88]:
print(classification_report(y_test, tree_param_pred))

              precision    recall  f1-score   support

           0       0.45      0.51      0.48        75
           1       0.60      0.55      0.57       102

    accuracy                           0.53       177
   macro avg       0.53      0.53      0.53       177
weighted avg       0.54      0.53      0.53       177



Stability of Electric Grid

In [101]:
import numpy as np
import pandas as pd
import graphviz
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set()
from sklearn import tree
from sklearn.metrics import accuracy_score
data=pd.read_csv('C:\\Users\\HP\\Downloads\\hamoye\\dataset\\Data_for_UCI_named.csv', delimiter = ',')
data.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [92]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import LeaveOneOut

In [93]:
from imblearn.over_sampling import SMOTE

In [94]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [95]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier

In [96]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [97]:
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [98]:
from sklearn import metrics

In [102]:
data.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [103]:
data['stabf'].value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [104]:
data.isnull().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

# Train Test Split

In [106]:
x=data.drop(columns=['stab','stabf'])
y=data['stabf']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
y_train.value_counts()

unstable    4464
stable      2536
Name: stabf, dtype: int64

# standardize the variable

In [110]:
scaler=StandardScaler()
normalized_train_df=scaler.fit_transform(x_train)
normalized_train_df=pd.DataFrame(normalized_train_df,columns=x_train.columns)
#normalize the test dataset
normalized_test_df=scaler.transform(x_test)
normalized_test_df=pd.DataFrame(normalized_test_df,columns=x_test.columns)

# 1)Building a random forest classification model

In [111]:
rfc=RandomForestClassifier(random_state=1)
rfc.fit(normalized_train_df,y_train)
predictions_rfc=rfc.predict(normalized_test_df)

# Feature importance(RFC)

In [112]:
featimp_rfc=zip(rfc.feature_importances_,x.columns)
sorted(featimp_rfc)

[(0.028735175431670392, 'p1'),
 (0.029005447698211183, 'p4'),
 (0.030423502581170304, 'p3'),
 (0.03149204237294532, 'p2'),
 (0.0920565983938599, 'g1'),
 (0.09543723073683505, 'g4'),
 (0.09751659190696522, 'g2'),
 (0.1001368336942113, 'g3'),
 (0.11751901475496626, 'tau3'),
 (0.12304702920019767, 'tau4'),
 (0.12567019362713266, 'tau1'),
 (0.1289603396018349, 'tau2')]

# Evaluation(RFC)

In [113]:
print(metrics.classification_report(y_test,predictions_rfc,digits=4))

              precision    recall  f1-score   support

      stable     0.9066    0.8598    0.8826      1084
    unstable     0.9229    0.9499    0.9362      1916

    accuracy                         0.9173      3000
   macro avg     0.9148    0.9048    0.9094      3000
weighted avg     0.9170    0.9173    0.9168      3000



In [114]:
print(metrics.confusion_matrix(y_test,predictions_rfc))

[[ 932  152]
 [  96 1820]]


# Accuracy

In [118]:
accuracy_rfc=metrics.accuracy_score(y_test,predictions_rfc)
print('Accuracy: {}'.format(round(accuracy_rfc *100 ,2)))

Accuracy: 91.73


# Precision

In [119]:
precision_rfc=metrics.precision_score(y_test,predictions_rfc,pos_label=('stable'))
print('Precision:{}'.format(round(precision_rfc*100,2)))

Precision:90.66


# Recall

In [120]:
recall_rfc=metrics.recall_score(y_test,predictions_rfc,pos_label=('stable'))
print('Recall:{}'.format(round(recall_rfc*100,2)))

Recall:85.98


# F1-score

In [121]:
f1_rfc=metrics.f1_score(y_test,predictions_rfc,pos_label=('stable'))
print('F1:{}'.format(round(f1_rfc*100),2))

F1:88


# 2)Building an extra trees classifier model

# Training and predicting

In [122]:
etc=ExtraTreesClassifier(random_state=1)
etc.fit(normalized_train_df,y_train)
predictions_etc=etc.predict(normalized_test_df)

# Feature Importance(ETC)

In [123]:
featureimp_etc=zip(etc.feature_importances_,x.columns)
sorted(featureimp_etc,reverse=True)

[(0.1205605685426397, 'tau1'),
 (0.11719744856716707, 'tau2'),
 (0.11571542332332893, 'tau4'),
 (0.11066518456621707, 'tau3'),
 (0.09647193165612745, 'g3'),
 (0.09477660239256296, 'g2'),
 (0.0933559207057236, 'g4'),
 (0.08871654944175081, 'g1'),
 (0.04128182221224024, 'p3'),
 (0.04085213214653268, 'p2'),
 (0.04080760159156925, 'p4'),
 (0.039598814854140275, 'p1')]

# Evaluation(etc)

In [124]:
print(metrics.classification_report(y_test,predictions_etc,digits=4))

              precision    recall  f1-score   support

      stable     0.9406    0.8330    0.8836      1084
    unstable     0.9113    0.9703    0.9398      1916

    accuracy                         0.9207      3000
   macro avg     0.9259    0.9016    0.9117      3000
weighted avg     0.9219    0.9207    0.9195      3000



In [125]:
print(metrics.confusion_matrix(y_test,predictions_etc))

[[ 903  181]
 [  57 1859]]


# Accuracy(etc)

In [128]:
accuracy_etc=metrics.accuracy_score(y_test,predictions_etc)
print('Accuracy:{}'.format(round(accuracy_etc*100,2)))

Accuracy:92.07


# Precision(etc)

In [131]:
precision_etc=metrics.precision_score(y_test,predictions_etc,pos_label=('stable'))
print('Precision:{}'.format(round(precision_etc*100,2)))

Precision:94.06


# Recall(etc)

In [132]:
recall_etc=metrics.recall_score(y_test,predictions_etc,pos_label=('stable'))
print('Recall:{}'.format(round(recall_etc*100,2)))

Recall:83.3


# f1-score(etc)

In [194]:
f1_etc=metrics.f1_score(y_test,predictions_etc,pos_label=('stable'))
print('F1:{}'.format(round(f1_score*100,2)))

F1:88.36


# 3)Building an Extra Tree Classifier with randomized cross validation search

In [136]:
param_distributions={'n_estimators':[50,100,300,500,1000],'min_samples_split':[2,3,5,7,9],'min_samples_leaf':[1,2,4,6,8],
                   'max_features':['auto','sqrt','log2',None],'random_state':[1]}
randomcv=RandomizedSearchCV(ExtraTreesClassifier(),param_distributions,n_iter=10,scoring='accuracy',n_jobs=-1,refit=True,
                           cv=5,verbose=1,random_state=1)
randomcv.fit(normalized_train_df,y_train)
predictions_randomcv=randomcv.predict(normalized_test_df)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  1.0min
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:  1.1min finished


In [137]:
randomcv.best_params_

{'random_state': 1,
 'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 8,
 'max_features': None}

In [139]:
randomcv.best_estimator_

ExtraTreesClassifier(max_features=None, min_samples_leaf=8, n_estimators=1000,
                     random_state=1)

In [140]:
randomcv.best_estimator_.feature_importances_

array([0.14161183, 0.14056496, 0.13212261, 0.13444839, 0.00379708,
       0.00559831, 0.00550506, 0.00511761, 0.10146189, 0.10808752,
       0.11374278, 0.10794198])

In [141]:
featureimp_randomcv=zip(randomcv.best_estimator_.feature_importances_,x.columns)
sorted(featureimp_randomcv,reverse=True)

[(0.14161182658459098, 'tau1'),
 (0.1405649589819013, 'tau2'),
 (0.13444839281821022, 'tau4'),
 (0.13212260507717843, 'tau3'),
 (0.11374277980352124, 'g3'),
 (0.1080875190422331, 'g2'),
 (0.10794198183194556, 'g4'),
 (0.10146188676683726, 'g1'),
 (0.005598311676953873, 'p2'),
 (0.0055050556643789494, 'p3'),
 (0.005117605099919773, 'p4'),
 (0.0037970766523292305, 'p1')]

# Evaluation(Randomizedcv)

In [142]:
print(metrics.classification_report(y_test,predictions_randomcv,digits=4))

              precision    recall  f1-score   support

      stable     0.9276    0.8625    0.8939      1084
    unstable     0.9252    0.9619    0.9432      1916

    accuracy                         0.9260      3000
   macro avg     0.9264    0.9122    0.9185      3000
weighted avg     0.9261    0.9260    0.9254      3000



In [143]:
print(metrics.confusion_matrix(y_test,predictions_randomcv))

[[ 935  149]
 [  73 1843]]


# Accuracy(randomizedcv)

In [144]:
accuracy_randomcv=metrics.accuracy_score(y_test,predictions_randomcv)
print('Accuracy:{}'.format(round(accuracy_randomcv*100,2)))

Accuracy:92.6


# Precision(randomizedcv)

In [146]:
precision_randomcv=metrics.precision_score(y_test,predictions_randomcv,pos_label=('stable'))
print('Precision:{}'.format(round(precision_randomcv*100,2)))

Precision:92.76


# Recall(randomizedcv)

In [147]:
recall_randomcv=metrics.recall_score(y_test,predictions_randomcv,pos_label=('stable'))
print('recall:{}'.format(round(recall_randomcv*100,2)))

recall:86.25


# f1_score(randomizedcv)

In [148]:
f1_randomcv=metrics.f1_score(y_test,predictions_randomcv,pos_label=('stable'))
print('f1_score:{}'.format(round(f1_randomcv*100,2)))

f1_score:89.39


# 4)Building an extreme gradient boosting model classifier(XGBC)

# Training and predicting

In [150]:
xgbc=XGBClassifier(max_depth=3,learning_rate=0.1,random_state=1)
xgbc.fit(normalized_train_df,y_train)
predictions_xgbc=xgbc.predict(normalized_test_df)

In [151]:
featimp_xgbc=zip(xgbc.feature_importances_,x.columns)
sorted(featimp_xgbc)

[(0.0, 'p3'),
 (0.0059235995, 'p4'),
 (0.007858184, 'p1'),
 (0.0136774285, 'p2'),
 (0.106959485, 'g4'),
 (0.10796254, 'g1'),
 (0.10975374, 'g2'),
 (0.1111254, 'g3'),
 (0.12752436, 'tau2'),
 (0.12947302, 'tau4'),
 (0.13789357, 'tau3'),
 (0.14184862, 'tau1')]

# Evaluation(xgbc)

In [152]:
print(metrics.classification_report(y_test,predictions_xgbc))

              precision    recall  f1-score   support

      stable       0.91      0.83      0.87      1084
    unstable       0.91      0.96      0.93      1916

    accuracy                           0.91      3000
   macro avg       0.91      0.89      0.90      3000
weighted avg       0.91      0.91      0.91      3000



In [153]:
print(metrics.confusion_matrix(y_test,predictions_xgbc))

[[ 903  181]
 [  86 1830]]


# Accuracy(xgbc)

In [155]:
accuracy_xgbc=metrics.accuracy_score(y_test,predictions_xgbc)
print('Accuracy: {}'.format(round(accuracy_xgbc*100,2)))

Accuracy: 91.1


# Precision(xgbc)

In [157]:
precision_xgbc=metrics.precision_score(y_test,predictions_xgbc,pos_label=('stable'))
print('Precison:{}'.format(round(precision_xgbc*100,2)))

Precison:91.3


# Recall(xgbc)

In [161]:
recall_xgbc=metrics.recall_score(y_test,predictions_xgbc,pos_label=('stable'))
print('Recall:{}'.format(round(recall_xgbc*100,2)))

Recall:83.3


# f1_score(xgbc)

In [162]:
f1_xgbc=metrics.f1_score(y_test,predictions_xgbc,pos_label=('stable'))
print('f1_score:{}'.format(round(f1_xgbc*100,2)))

f1_score:87.12


# 5)Building a light gradient boosting model(LGBM)

# Training and Predicting

In [176]:
lgbm=LGBMClassifier(random_state=1)
lgbm.fit(normalized_train_df,y_train)
predictions_lgbm=lgbm.predict(normalized_test_df)

In [177]:
featureimp_lgbm=zip(lgbm.feature_importances_,x.columns)
sorted(featureimp_lgbm,reverse=True)

[(385, 'tau1'),
 (373, 'tau3'),
 (372, 'tau2'),
 (370, 'tau4'),
 (364, 'g1'),
 (354, 'g3'),
 (343, 'g4'),
 (326, 'g2'),
 (38, 'p3'),
 (27, 'p2'),
 (25, 'p4'),
 (23, 'p1')]

# Evaluation(lgbm)

In [181]:
print(metrics.classification_report(y_test, predictions_lgbm, digits=4))

              precision    recall  f1-score   support

      stable     0.9223    0.9087    0.9154      1084
    unstable     0.9488    0.9567    0.9527      1916

    accuracy                         0.9393      3000
   macro avg     0.9355    0.9327    0.9341      3000
weighted avg     0.9392    0.9393    0.9392      3000



In [183]:
print(metrics.confusion_matrix(y_test,predictions_lgbm))

[[ 985   99]
 [  83 1833]]


# Accuracy(lgbm)

In [185]:
accuracy_lgbm=metrics.accuracy_score(y_test,predictions_lgbm)
print('Accuracy:{}'.format(round(accuracy_lgbm*100,2)))

Accuracy:93.93


# Precision(lgbm)

In [189]:
precision_lgbm=metrics.precision_score(y_test,predictions_lgbm,pos_label=('stable'))
print('Precision:{}'.format(round(precision_lgbm*100,2)))

Precision:92.23


# Recall(lgbm)

In [190]:
recall_lgbm=metrics.recall_score(y_test,predictions_lgbm,pos_label=('stable'))
print('Recall:{}'.format(round(recall_lgbm*100,2)))

Recall:90.87


# F1-score(lgbm)

In [193]:
f1_lgbm=metrics.f1_score(y_test,predictions_lgbm,pos_label=('stable'))
print('F1:{}'.format(round(f1_lgbm*100,2)))

F1:91.54


# Comparing Evalution Reports for the 'stable' class

In [197]:
stable_dict={'Classifier':['Random Forest Classifier','Extra Trees Classifier','ExtraTrees Randomized Cv',
'Extra Gradient Boost model','Light Gradient Boost Model'], 'Accuracy':[accuracy_rfc,accuracy_etc,accuracy_randomcv,
accuracy_xgbc,accuracy_lgbm],'Precision':[precision_rfc,precision_etc,precision_randomcv,precision_xgbc,precision_lgbm],
'Recall':[recall_rfc,recall_etc,recall_randomcv,recall_xgbc,recall_lgbm],'F1-score':[f1_rfc,f1_etc,f1_randomcv,f1_xgbc,f1_lgbm]}
result=pd.DataFrame(stable_dict)
result.set_index('Classifier',inplace=True)
result

Accuracy  Precision    Recall  F1-score
Classifier                                                         
Random Forest Classifier    0.917333   0.906615  0.859779  0.882576
Extra Trees Classifier      0.920667   0.940625  0.833026  0.883562
ExtraTrees Randomized Cv    0.926000   0.927579  0.862546  0.893881
Extra Gradient Boost model  0.911000   0.913043  0.833026  0.871201
Light Gradient Boost Model  0.939333   0.922285  0.908672  0.915428